# Generated by Django 5.2.8 on 2025-11-23 01:55

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=12)),
                ('genre', models.CharField(choices=[('Homme', 'Masculin'), ('Femme', 'Féminin')], default='Homme', max_length=30)),
                ('date_naissance', models.DateField()),
                ('profession', models.CharField(max_length=100)),
                ('groupe_sanguin', models.CharField(max_length=12)),
                ('poids', models.CharField(max_length=12)),
                ('taille', models.CharField(max_length=12)),
                ('pays', django_countries.fields.CountryField(default='SN', max_length=2)),
                ('province', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('ville_commune', models.CharField(max_length=60)),
                ('code_postal', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=100)),
                ('cni_recto', models.CharField(max_length=30)),
                ('cni_verso', models.CharField(max_length=30)),
                ('num_passport', models.CharField(max_length=30)),
                ('num_ninea', models.CharField(max_length=30)),
                ('num_rccm', models.CharField(max_length=30)),
                ('num_permis', models.CharField(max_length=30)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['-date'],
            },
        ),
    ]
